[package]
name = "cmtir"
edition.workspace = true
version.workspace = true
authors.workspace = true
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
description = "The intermediate representation for Cement (cmt2) languages and compiler tools."

[dependencies]
kir = { path = "../kir", version = "^0.1.0" }
location-macros = "0.1.2"
log = "0.4.22"
num = "0.4.3"
slotmap = "1.0.6"
regex = "1.11.0"
serde = { version = "1.0.215", features = ["std", "derive"] }
# fir = { path = "../fir" }
indexmap.workspace = true
itertools = "0.14.0"
json = "0.12.4"
chrono = "0.4.38"
colored = "3.0.0"
env_logger = "0.11.5"
proc-macro2 = { version = "1.0.92", features = [
    "span-locations",
    "proc-macro",
] }
ariadne = { version = "0.5.0", features = ["auto-color"] }
anyhow = "1.0.95"
