[package]
name = "irony"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rustc-hash = "1.1.0"
indexmap = "2.0.0"

paste = "1.0.14"
visible = "0.0.1"
